# Generated by Django 5.2.1 on 2025-05-30 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_order_delivery_address_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfood',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='managed_fast_foods', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
