# Generated by Django 5.2.1 on 2025-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_fastfood_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ristoratore',
            field=models.BooleanField(default=False),
        ),
    ]
