# Generated by Django 5.2.1 on 2025-06-04 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='revealed_by',
            field=models.ManyToManyField(blank=True, related_name='revealed_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
