# Generated by Django 5.2.1 on 2025-06-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='revealed_by',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
