# Generated by Django 5.2.1 on 2025-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0011_remove_coupon_revealed_by_coupon_is_revealed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_revealed',
        ),
        migrations.AddField(
            model_name='user',
            name='revealed_coupons',
            field=models.ManyToManyField(blank=True, to='gestione.coupon'),
        ),
    ]
