# Generated by Django 5.2.1 on 2025-06-10 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0012_remove_coupon_is_revealed_user_revealed_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_coupons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='revealed_coupons',
            field=models.ManyToManyField(blank=True, related_name='revealed_by_users', to='gestione.coupon'),
        ),
    ]
