# Generated by Django 5.2.1 on 2025-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0013_coupon_user_alter_user_revealed_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastfood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastfood',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
