# Generated by Django 5.2.1 on 2025-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0014_remove_fastfood_city_remove_fastfood_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastfood',
            old_name='address',
            new_name='indirizzo',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='latitude',
            new_name='latitudine',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='longitude',
            new_name='longitudine',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='name',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='nome',
            field=models.CharField(default=19, max_length=100),
            preserve_default=False,
        ),
    ]
