# Generated by Django 5.2.1 on 2025-06-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0015_rename_address_fastfood_indirizzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
