# Generated by Django 5.2.1 on 2025-06-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0016_alter_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastfood',
            old_name='indirizzo',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='nome',
            new_name='name',
        ),
    ]
